// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnLfQdvat4HRnR7dyHcQJ1NCxLWB4g5k',
    appId: '1:943651103979:web:78c2a324cdb571395f8aae',
    messagingSenderId: '943651103979',
    projectId: 'fluttertictactoe',
    authDomain: 'fluttertictactoe.firebaseapp.com',
    databaseURL: 'https://fluttertictactoe.firebaseio.com',
    storageBucket: 'fluttertictactoe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8M05Y9IIE9Kl_ckS1M4sPkkXulxAW0I',
    appId: '1:943651103979:android:dbc4129e84c758ba5f8aae',
    messagingSenderId: '943651103979',
    projectId: 'fluttertictactoe',
    databaseURL: 'https://fluttertictactoe.firebaseio.com',
    storageBucket: 'fluttertictactoe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSiVZFUmebpePLQBjzWPVcWWma38g-uRM',
    appId: '1:943651103979:ios:5f5bb97b8399ef595f8aae',
    messagingSenderId: '943651103979',
    projectId: 'fluttertictactoe',
    databaseURL: 'https://fluttertictactoe.firebaseio.com',
    storageBucket: 'fluttertictactoe.appspot.com',
    iosBundleId: 'com.dmilicic.tictactoe2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSiVZFUmebpePLQBjzWPVcWWma38g-uRM',
    appId: '1:943651103979:ios:3887d571b1117ef45f8aae',
    messagingSenderId: '943651103979',
    projectId: 'fluttertictactoe',
    databaseURL: 'https://fluttertictactoe.firebaseio.com',
    storageBucket: 'fluttertictactoe.appspot.com',
    iosBundleId: 'com.dmilicic.tictactoe2.RunnerTests',
  );
}
